apiVersion: v2
name: flask-app
description: A Helm chart for deploying a Flask application to Kubernetes

type: application
version: 0.1.0            # Chart version
appVersion: "1.0.0"       # Version of the actual app (your Flask app)
