replicaCount: 1

image:
  repository: ""
  tag: "latest"
  pullPolicy: Always

env: default

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
