apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flask-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "flask-app.name" . }}
    env: {{ .Values.env }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "flask-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "flask-app.name" . }}
        env: {{ .Values.env }}
    spec:
      containers:
        - name: {{ include "flask-app.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
