name: Deploy to EKS

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose the environment to deploy to"
        required: true
        default: dev
        type: choice
        options:
          - dev
          - test
          - prod

jobs:
  deploy:
    name: Deploy to ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REPO_NAME: ${{ secrets.ECR_REPO_NAME }}
      ENV: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name flask-cluster --region $AWS_REGION

      - name: Deploy using Helm
        run: |
          helm upgrade --install flask-${{ env.ENV }} ./charts/flask-app \
            --namespace ${{ env.ENV }} \
            --create-namespace \
            -f charts/flask-app/values-${{ env.ENV }}.yaml \
            --set image.repository=${{ secrets.ECR_URI }} \
            --set image.tag=${{ github.sha }}
